import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "my-component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <metadata />
      </Head>

      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </>
  );
}
